Repository openshift/sdn, pull requests merged in 2019-11, with the labels that each got.

#60 UPSTREAM 83911: Fix DeltaFIFO Replace method
  glide.diff
  vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo_test.go
Labels: approved, lgtm, size/M

#62 sdn-cni-plugin built without openssl and cgo
  images/node/Dockerfile.rhel
Labels: approved, lgtm, size/XS

#64 client: Use protobuf for SDN clients
  pkg/openshift-sdn/informers.go
Labels: approved, lgtm, size/XS

#67 Simplify CNI plugin build, copy updated rules to images/sdn/
  images/node/Dockerfile.rhel
  images/sdn/Dockerfile.rhel
Labels: approved, lgtm, size/S

#69 Bug 1768926: Ignore unsupported NetworkPolicy rules, rather than treating them as errors
  pkg/network/node/networkpolicy.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#66 Add IPv6 support and multiple CIDR support to SubnetAllocator
  pkg/network/master/master.go
  pkg/network/master/subnet_allocator.go
  pkg/network/master/subnet_allocator_test.go
  pkg/network/master/subnets.go
  pkg/network/master/util/subnet_allocator.go
  pkg/network/master/util/subnet_allocator_test.go
Labels: approved, lgtm, size/XXL

#70 Additional event logging for add/delete/update informer events
  pkg/openshift-sdn/informers.go
Labels: approved, lgtm, size/M

#56 Bug 1768436: UPSTREAM: 74840: kube-proxy: Drop packets in INVALID state
  glide.diff
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S
