Repository openshift/sdn, pull requests merged in 2019-09, with the labels that each got.

#29 Remove one layer of proxy wrapping
  pkg/network/proxy/proxy.go
  pkg/openshift-sdn/proxy.go
Labels: approved, lgtm, size/L

#34 Bug 1751954: images: disable cgo
  images/node/Dockerfile.rhel
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#36 Bug 1752636: networkpolicy: add a namespaceSelector cache
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL
