Repository openshift/sdn, pull requests merged in 2019-07, with the labels that each got.

#4 Fix Makefile and .gitignore
  .gitignore
  Makefile
Labels: lgtm, size/S

#7 Add arping to openshift-sdn image
  images/node/Dockerfile
  images/node/Dockerfile.rhel
Labels: approved, lgtm, size/XS

#6 Route to SDN irrespective if macvlan mode is used or not
  cmd/sdn-cni-plugin/openshift-sdn_linux.go
Labels: approved, lgtm, size/S

#9 Initial README
  README.md
Labels: approved, lgtm, size/M

#13 Bug 1726045: skip OPENSHIFT-MASQ for traffic already marked for masquerade
  pkg/network/node/iptables.go
  pkg/network/node/node.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#12 Allow DNS port when performing iptables filtering on cloud provider metadata IP
  cmd/sdn-cni-plugin/openshift-sdn_linux.go
  pkg/network/node/ovscontroller.go
Labels: approved, lgtm, size/S

#11 Untaint node on startup if node is tainted and MTU is ok
  pkg/network/node/node.go
Labels: approved, lgtm, size/M

#14 Add kube-proxy image
  .gitignore
  Makefile
  images/iptables-scripts/ip6tables
  images/iptables-scripts/ip6tables-restore
  images/iptables-scripts/ip6tables-save
  images/iptables-scripts/iptables
  images/iptables-scripts/iptables-restore
  images/iptables-scripts/iptables-save
  images/kube-proxy/Dockerfile
  images/kube-proxy/Dockerfile.rhel
  images/kube-proxy/scripts/ip6tables
  images/kube-proxy/scripts/ip6tables-restore
  images/kube-proxy/scripts/ip6tables-save
  images/kube-proxy/scripts/iptables
  images/kube-proxy/scripts/iptables-restore
  images/kube-proxy/scripts/iptables-save
  images/node/Dockerfile
  images/node/Dockerfile.rhel
Labels: approved, lgtm, size/M

#17 iptables: partial #13 revert, skip masq in chain
  pkg/network/node/iptables.go
Labels: approved, lgtm, size/S

#8 Unidling: minimize iptables lock contention
  glide.lock
  pkg/network/proxy/proxy.go
  pkg/network/proxyimpl/hybrid/proxy.go
  pkg/openshift-sdn/proxy.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/golang.mk
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/images.mk
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/k8s.io/kubernetes/cmd/kube-proxy/app/server.go
  vendor/k8s.io/kubernetes/cmd/kube-proxy/app/server_others.go
  vendor/k8s.io/kubernetes/cmd/kube-proxy/app/server_windows.go
  vendor/k8s.io/kubernetes/pkg/kubemark/BUILD
  vendor/k8s.io/kubernetes/pkg/kubemark/hollow_proxy.go
  vendor/k8s.io/kubernetes/pkg/proxy/BUILD
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier_openshift.go
  vendor/k8s.io/kubernetes/pkg/proxy/types.go
  vendor/k8s.io/kubernetes/pkg/proxy/userspace/BUILD
  vendor/k8s.io/kubernetes/pkg/proxy/userspace/loadbalancer.go
  vendor/k8s.io/kubernetes/pkg/proxy/userspace/proxier.go
  vendor/k8s.io/kubernetes/pkg/proxy/userspace/proxier_openshift.go
  vendor/k8s.io/kubernetes/pkg/proxy/userspace/proxier_test.go
  vendor/k8s.io/kubernetes/pkg/proxy/winuserspace/BUILD
  vendor/k8s.io/kubernetes/pkg/proxy/winuserspace/loadbalancer.go
  vendor/k8s.io/kubernetes/pkg/proxy/winuserspace/proxier.go
Labels: approved, lgtm, size/XXL

#18 Drop accidentally not-dropped duplicate iptables scripts
  images/kube-proxy/scripts/ip6tables
  images/kube-proxy/scripts/ip6tables-restore
  images/kube-proxy/scripts/ip6tables-save
  images/kube-proxy/scripts/iptables
  images/kube-proxy/scripts/iptables-restore
  images/kube-proxy/scripts/iptables-save
Labels: approved, lgtm, size/S
