Repository openshift/sdn, pull requests merged in 2019-12, with the labels that each got.

#32 how to do a Kubernetes rebase
  HACKING.md
Labels: approved, lgtm, size/L

#76 Remove some gratuitous CIDR unparsing and reparsing
  pkg/network/common/common.go
  pkg/network/common/validation.go
Labels: approved, lgtm, size/S

#57 slightly improve logging
  pkg/network/node/pod.go
  pkg/network/node/vnids.go
Labels: approved, lgtm, size/S

#73 Bug 1772905: [4.2] Clean up egress IPs on startup
  pkg/network/common/egressip.go
  pkg/network/common/egressip_test.go
  pkg/network/master/egressip.go
  pkg/network/node/egressip.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#79 proxy: add handler with same ResyncPeriod as shared informer.
  pkg/openshift-sdn/proxy.go
Labels: approved, lgtm, size/XS

#84 Bug 1782847: sdn: undo debug logging
  pkg/openshift-sdn/informers.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#82 Bug 1780387: host-local plugin should be built and executed within container
  .gitignore
  Makefile
  images/node/Dockerfile.rhel
  images/sdn/Dockerfile.fedora
  images/sdn/Dockerfile.rhel
  pkg/network/node/pod.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#83 Bug 1782312: [backport] host-local plugin should be built and executed within container
  .gitignore
  Makefile
  images/node/Dockerfile.rhel
  images/sdn/Dockerfile.fedora
  images/sdn/Dockerfile.rhel
  pkg/network/node/pod.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#86 Drop old separate node/controller images
  Makefile
  README.md
  images/node/Dockerfile.rhel
  images/sdn-controller/Dockerfile.rhel
Labels: approved, lgtm, size/M
