Repository openshift/sdn, pull requests merged in 2019-10, with the labels that each got.

#42 further NetworkPolicy caching fixes
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
Labels: approved, lgtm, size/L

#46 update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#26 Add support for IPBlocks
  pkg/network/node/networkpolicy.go
Labels: approved, lgtm, needs-ok-to-test, size/S

#49 Bug 1751458: Fix parsing of IFLA_GRE_COLLECT_METADATA
  glide.diff
  vendor/github.com/vishvananda/netlink/link_linux.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#48 Make DNS querying more efficient by querying once per dns name
  pkg/network/common/dns.go
  pkg/network/common/dns_test.go
  pkg/network/common/egress_dns.go
  pkg/network/node/egress_network_policy.go
  pkg/network/node/node.go
  pkg/network/node/ovscontroller.go
  pkg/network/proxy/proxy.go
Labels: approved, lgtm, size/L

#51 Bug 1753216: Clean up egress IPs on startup
  pkg/network/common/egressip.go
  pkg/network/common/egressip_test.go
  pkg/network/master/egressip.go
  pkg/network/node/egressip.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#52 Bug 1760103: Adjust SDN setup so AlreadySetUp check will fail on a half-set-up node
  pkg/network/node/node.go
  pkg/network/node/ovscontroller.go
  pkg/network/node/sdn_controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#54 Remove watching Endpoints of Headless Services
  pkg/openshift-sdn/informers.go
Labels: approved, lgtm, size/S

#50 Bug 1759831: Fix parsing of IFLA_GRE_COLLECT_METADATA
  glide.diff
  vendor/github.com/vishvananda/netlink/link_linux.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#45 Bug 1758232: NetworkPolicy performance fixes [4.2]
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XL

#59 Create a merged node/master image
  Makefile
  images/kube-proxy/Dockerfile
  images/sdn-controller/Dockerfile
  images/sdn/Dockerfile.fedora
  images/sdn/Dockerfile.rhel
Labels: approved, lgtm, size/L
