Repository openshift/sdn, pull requests merged in 2019-08, with the labels that each got.

#21 Dockerfiles: verify that packages are installed
  images/node/Dockerfile
  images/node/Dockerfile.rhel
Labels: approved, lgtm, size/XS

#19 Bug 1700431: Pass egress IP packets to conntrack
  pkg/network/node/ovscontroller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#23 proxy: add a bit more logging around proxy type and sync status
  pkg/network/proxyimpl/hybrid/proxy.go
  pkg/openshift-sdn/proxy.go
Labels: approved, lgtm, size/XS

#22 add LICENSE
  LICENSE
Labels: approved, lgtm, size/L

#20 Bug 1740741: Initializing runningPods on SDN bootup for 4.x
  pkg/network/node/multitenant.go
  pkg/network/node/node.go
  pkg/network/node/ovscontroller.go
  pkg/network/node/pod.go
  pkg/network/node/sdn_controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#24 Stop building CNI loopback and host-local plugins
  .gitignore
  Makefile
  images/node/Dockerfile
  images/node/Dockerfile.rhel
  pkg/network/node/node.go
  pkg/network/node/pod.go
Labels: approved, lgtm, size/S

#27 Do not cache egressLink details
  pkg/network/node/egressip.go
Labels: approved, lgtm, size/M
