Repository openshift/sdn, pull requests merged in 2020-07, with the labels that each got.

#153 Bug 1851182: Retry commiting OVS transactions in case of failure
  pkg/network/node/metrics/metrics.go
  pkg/network/node/node.go
  pkg/network/node/ovs/fake_ovs.go
  pkg/network/node/ovs/ovs.go
  pkg/network/node/ovs/ovs_test.go
  pkg/network/node/pod.go
  pkg/network/node/vnids.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#158 Add support for --may-exist when adding the bridge in sdn
  pkg/network/node/ovs/fake_ovs.go
  pkg/network/node/ovs/ovs.go
  pkg/network/node/ovscontroller.go
Labels: approved, lgtm

#159 Retry all OVS executions, not only transactions
  pkg/network/node/ovs/ovs.go
  pkg/network/node/ovs/ovs_test.go
Labels: approved, lgtm

#154 Bug 1853193: [release-4.5] Backport OVS-retries
  pkg/network/node/metrics/metrics.go
  pkg/network/node/node.go
  pkg/network/node/ovs/fake_ovs.go
  pkg/network/node/ovs/ovs.go
  pkg/network/node/ovs/ovs_test.go
  pkg/network/node/pod.go
  pkg/network/node/vnids.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#165 Remove unused packages from Dockerfile
  images/sdn/Dockerfile.rhel
Labels: approved, lgtm

#166 Bug 1855119: [release-4.4] Add support for --may-exist when adding the bridge in sdn
  pkg/network/node/ovs/fake_ovs.go
  pkg/network/node/ovs/ovs.go
  pkg/network/node/ovscontroller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#155 Bug 1853197: [release-4.4] Backport OVS-retries
  pkg/network/node/metrics/metrics.go
  pkg/network/node/node.go
  pkg/network/node/ovs/fake_ovs.go
  pkg/network/node/ovs/ovs.go
  pkg/network/node/ovs/ovs_test.go
  pkg/network/node/pod.go
  pkg/network/node/vnids.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm
