Repository openshift/sdn, pull requests merged in 2020-08, with the labels that each got.

#156 Bug 1853198: [release-4.3] Backport OVS-retries
  pkg/network/node/metrics/metrics.go
  pkg/network/node/node.go
  pkg/network/node/ovs/fake_ovs.go
  pkg/network/node/ovs/ovs.go
  pkg/network/node/ovs/ovs_test.go
  pkg/network/node/pod.go
  pkg/network/node/vnids.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#167 Bug 1859869: [release-4.3] Add support for --may-exist when adding the bridge in sdn
  pkg/network/node/ovs/fake_ovs.go
  pkg/network/node/ovs/ovs.go
  pkg/network/node/ovscontroller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#172 Bug 1857743: Port stuck open when ep deleted before svc in unidling mode
  pkg/network/proxyimpl/hybrid/proxy.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#171 Bug 1859451: Add NodeInformer to EgressIP
  pkg/network/master/egressip.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#175 Bug 1871732: Fix nodeInformer call in EgressIPManager.
  pkg/network/master/egressip.go
  pkg/network/master/master.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
