Repository openshift/sdn, pull requests merged in 2020-03, with the labels that each got.

#101 Bug 1797043: [4.2] Clean up stale egress IP iptables rules on startup
  pkg/network/node/egressip.go
  pkg/network/node/iptables.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#39 Bug 1801737: drop firewalld monitoring, add better iptables monitor
  glide.diff
  pkg/network/node/iptables.go
  pkg/openshift-sdn/proxy.go
  vendor/k8s.io/kubernetes/cmd/kube-proxy/app/BUILD
  vendor/k8s.io/kubernetes/cmd/kube-proxy/app/server_others.go
  vendor/k8s.io/kubernetes/cmd/kubeadm/.import-restrictions
  vendor/k8s.io/kubernetes/go.mod
  vendor/k8s.io/kubernetes/pkg/kubelet/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/network/hostport/fake_iptables.go
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/network/kubenet/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_network_linux.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_network_others.go
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier_openshift.go
  vendor/k8s.io/kubernetes/pkg/util/BUILD
  vendor/k8s.io/kubernetes/pkg/util/dbus/BUILD
  vendor/k8s.io/kubernetes/pkg/util/dbus/dbus.go
  vendor/k8s.io/kubernetes/pkg/util/dbus/dbus_test.go
  vendor/k8s.io/kubernetes/pkg/util/dbus/doc.go
  vendor/k8s.io/kubernetes/pkg/util/dbus/fake_dbus.go
  vendor/k8s.io/kubernetes/pkg/util/iptables/BUILD
  vendor/k8s.io/kubernetes/pkg/util/iptables/iptables.go
  vendor/k8s.io/kubernetes/pkg/util/iptables/iptables_test.go
  vendor/k8s.io/kubernetes/pkg/util/iptables/monitor_test.go
  vendor/k8s.io/kubernetes/pkg/util/iptables/testing/fake.go
  vendor/k8s.io/kubernetes/test/test_owners.csv
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XXL

#115 Bug 1810505: Pass -w to iptables when adding anti-metadata-server rules
  cmd/sdn-cni-plugin/openshift-sdn_linux.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#107 Do not check err, but ok for K8S_POD_NAMESPACE and K8S_POD_NAME
  pkg/network/node/cniserver/cniserver.go
Labels: approved, lgtm, ok-to-test, size/XS

#114 Bug 1811739: Fix kube_proxy metrics
  pkg/network/node/metrics.go
  pkg/openshift-sdn/proxy.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#119 proxy: It should be possible to enable the profiling endpoint
  pkg/openshift-sdn/proxy.go
Labels: approved, lgtm, size/XS

#120 Add --node-name and --node-ip flags to openshift-sdn-node
  pkg/network/node/node.go
  pkg/openshift-sdn/cmd.go
  pkg/openshift-sdn/proxy.go
  pkg/openshift-sdn/sdn.go
Labels: approved, lgtm

#122 Bug 1813846: handle default-deny rule properely
  pkg/network/node/networkpolicy.go
Labels: approved, bugzilla/valid-bug, lgtm

#121 Drop --url-only-kubeconfig, require --node-name / --node-ip
  pkg/network/node/node.go
  pkg/openshift-sdn/cmd.go
  pkg/openshift-sdn/proxy.go
Labels: approved, lgtm
