Repository openshift/sdn, pull requests merged in 2020-10, with the labels that each got.

#197 Bug 1878787: vxlan_monitor_test: fix flake
  go.mod
  go.sum
  pkg/network/node/vxlan_monitor_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#185 Add documentation to openshift/sdn
  docs/Dockerfile
  docs/requirements.txt
  docs/source/conf.py
  docs/source/favicon.png
  docs/source/index.rst
  docs/source/openshift_sdn/README.md
  docs/source/openshift_sdn/index.rst
  docs/source/openshift_sdn/workflow.rst
Labels: approved, lgtm

#164 update egress dns code for dual-stack...
  pkg/network/common/dns.go
  pkg/network/common/dns_test.go
  pkg/network/common/egress_dns.go
  pkg/network/node/node.go
  pkg/network/proxy/proxy.go
Labels: approved, lgtm

#198 Allow running openshift-sdn with standalone kube-proxy
  pkg/openshift-sdn/cmd.go
  pkg/openshift-sdn/proxy.go
Labels: approved, lgtm

#200 Updating kube-proxy builder & base images to be consistent with ART
  images/kube-proxy/Dockerfile.rhel
Labels: approved, lgtm

#199 Updating ose-sdn builder & base images to be consistent with ART
  images/sdn/Dockerfile.rhel
Labels: approved, lgtm

#202 Run metrics when using standalone kube-proxy
  pkg/openshift-sdn/proxy.go
Labels: approved, lgtm

#204 Bug 1878845: Fix ruleversion
  pkg/network/node/ovscontroller.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#208 Owners: Remove Phil from reviewers
  OWNERS
Labels: approved, lgtm
