Repository openshift/sdn, pull requests merged in 2020-05, with the labels that each got.

#138 Bug 1826339: vendor: bump our k8s vendor
  go.mod
  go.sum
  vendor/go.uber.org/atomic/.travis.yml
  vendor/go.uber.org/atomic/README.md
  vendor/go.uber.org/atomic/error.go
  vendor/go.uber.org/multierr/.travis.yml
  vendor/go.uber.org/multierr/error.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/validation/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go
  vendor/k8s.io/kubernetes/pkg/proxy/metrics/metrics.go
  vendor/k8s.io/kubernetes/pkg/proxy/winkernel/proxier.go
  vendor/k8s.io/kubernetes/pkg/volume/BUILD
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#139 Bug 1824203: Fix egressVXLANMonitor and egressIPTracker deadlock
  pkg/network/node/egressip.go
  pkg/network/node/vxlan_monitor.go
  pkg/network/node/vxlan_monitor_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#145 [release-4.4] Bug 1840215: Fix egressVXLANMonitor and egressIPTracker deadlock
  pkg/network/node/egressip.go
  pkg/network/node/vxlan_monitor.go
  pkg/network/node/vxlan_monitor_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#143 Bug 1839107: node/vnids: Correctly handle case where NetNamespace watch is far behind
  pkg/network/node/networkpolicy.go
  pkg/network/node/vnids.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
