Repository openshift/sdn, pull requests merged in 2020-02, with the labels that each got.

#72 Bug 1772592: Make DNS querying more efficient by querying once per dns name
  pkg/network/common/dns.go
  pkg/network/common/dns_test.go
  pkg/network/common/egress_dns.go
  pkg/network/node/egress_network_policy.go
  pkg/network/node/node.go
  pkg/network/node/ovscontroller.go
  pkg/network/proxy/proxy.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#103 Bug 1796157: Fix handling of VNID 0 with NetworkPolicy
  pkg/network/node/ovscontroller.go
  pkg/network/node/ovscontroller_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#105 Bug 1793952: [4.2] Fix reinitialization of deny-all NetworkPolicy state on restart
  pkg/network/node/ovscontroller.go
  pkg/network/node/ovscontroller_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#106 Bug 1804178: Revert excessive proxy logging
  pkg/network/proxy/proxy.go
  pkg/network/proxyimpl/hybrid/proxy.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#100 Bug 1797042: [4.3] Clean up stale egress IP iptables rules on startup
  pkg/network/node/egressip.go
  pkg/network/node/iptables.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#110 Bug 1806648: Fix pod startup reattach/kill loop
  pkg/network/node/node.go
  pkg/network/node/ovscontroller.go
  pkg/network/node/runtime.go
  pkg/network/node/sdn_controller.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M
