Repository openshift/sdn, pull requests merged in 2020-04, with the labels that each got.

#125 OWNERS: add bugzilla info
  OWNERS
Labels: approved, lgtm

#124 Bug 1816394: handle pod updates correctly in networkpolicy
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#126 Bug 1820778: fix health check in standalone kube-proxy
  glide.diff
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#128 [release-4.4] Bug 1816392: handle pod updates correctly in networkpolicy
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#117 Bug 1812052: Update HACKING.md rebase to use go modules
  HACKING.md
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#127 Bug 1822351: Fix hybrid proxier for iptables.Monitor
  pkg/network/node/iptables.go
  pkg/network/node/node.go
  pkg/network/proxy/proxy.go
  pkg/network/proxyimpl/hybrid/proxy.go
  pkg/openshift-sdn/cmd.go
  pkg/openshift-sdn/proxy.go
  pkg/openshift-sdn/sdn.go
Labels: approved, bugzilla/valid-bug, lgtm

#129 [release-4.3] Bug 1816390: handle pod updates correctly in networkpolicy
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#130 [release-4.2] Bug 1816389: handle pod updates correctly in networkpolicy
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#132 Bug 1824203: Make egressVXLANMonitor updates channel buffered
  pkg/network/node/egressip.go
Labels: approved, bugzilla/valid-bug, lgtm

#134 Bug 1825355: node/vnids: Correctly handle case where NetNamespace watch is far behind
  pkg/network/node/networkpolicy.go
  pkg/network/node/vnids.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
