Repository openshift/sdn, pull requests merged in 2020-09, with the labels that each got.

#169 Bug 1848478: Invalid egressCIDR value causes sdn pods to fail on startup
  pkg/network/common/common_test.go
  pkg/network/common/egressip.go
  pkg/network/common/validation.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#182 [release-4.5] Bug 1874798: Add NodeInformer to EgressIP
  pkg/network/master/egressip.go
  pkg/network/master/master.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#186 Bug 1878731: vxlan_monitor_test: fix flake
  pkg/network/node/vxlan_monitor_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#183 [release-4.4] Bug 1874799: Add NodeInformer to EgressIP
  pkg/network/master/egressip.go
  pkg/network/master/master.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#189 Bug 1762580: Enable conntrack for ovs-multitenant unless userspace proxy
  pkg/network/node/node.go
  pkg/network/node/ovs/ovs.go
  pkg/network/node/ovs/ovs_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#194 Bug 1877794: Emit a warning and ignore if empty cidr is passed to kubeproxy
  pkg/openshift-sdn/proxy.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#196 Bug 1882071: Fix bug in reflector not recovering from "Too large resource version"
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/fieldmanager.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/internal/managedfields.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/structuredmerge.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/update.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/BUILD
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/healthz/BUILD
  vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go
  vendor/k8s.io/apiserver/pkg/storage/errors.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/cloud-provider/go.sum
  vendor/k8s.io/kube-openapi/pkg/util/proto/validation/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/kubelet/types/constants.go
  vendor/k8s.io/kubernetes/pkg/kubelet/types/types.go
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go
  vendor/k8s.io/kubernetes/pkg/proxy/metrics/metrics.go
  vendor/k8s.io/kubernetes/pkg/proxy/winkernel/proxier.go
  vendor/k8s.io/kubernetes/pkg/util/ipvs/BUILD
  vendor/k8s.io/kubernetes/pkg/util/ipvs/ipvs_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/plugins.go
  vendor/k8s.io/kubernetes/third_party/forked/ipvs/BUILD
  vendor/k8s.io/kubernetes/third_party/forked/ipvs/LICENSE
  vendor/k8s.io/kubernetes/third_party/forked/ipvs/constants.go
  vendor/k8s.io/kubernetes/third_party/forked/ipvs/ipvs.go
  vendor/k8s.io/kubernetes/third_party/forked/ipvs/netlink.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
