Repository openshift/sdn, pull requests merged in 2020-11, with the labels that each got.

#209 Bug 1890130: fix pod creation deadlock
  pkg/network/node/pod.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#207 Modifications for klog v2.
  go.mod
  go.sum
  pkg/network/common/egress_dns.go
  pkg/network/common/egressip.go
  pkg/network/master/egressip.go
  pkg/network/master/master.go
  pkg/network/master/subnets.go
  pkg/network/master/vnids.go
  pkg/network/node/cniserver/cniserver.go
  pkg/network/node/egress_network_policy.go
  pkg/network/node/egressip.go
  pkg/network/node/healthcheck.go
  pkg/network/node/iptables.go
  pkg/network/node/multitenant.go
  pkg/network/node/networkpolicy.go
  pkg/network/node/node.go
  pkg/network/node/ovs/ovs.go
  pkg/network/node/ovscontroller.go
  pkg/network/node/pod.go
  pkg/network/node/runtime.go
  pkg/network/node/sdn_controller.go
  pkg/network/node/subnets.go
  pkg/network/node/vnids.go
  pkg/network/node/vxlan_monitor.go
  pkg/network/proxy/proxy.go
  pkg/network/proxyimpl/hybrid/proxy.go
  pkg/network/proxyimpl/unidler/unidlersocket.go
  pkg/openshift-network-controller/cmd.go
  pkg/openshift-network-controller/network_controller.go
  pkg/openshift-sdn/cmd.go
  pkg/openshift-sdn/proxy.go
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/klog/v2/.gitignore
  vendor/k8s.io/klog/v2/CONTRIBUTING.md
  vendor/k8s.io/klog/v2/LICENSE
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/RELEASE.md
  vendor/k8s.io/klog/v2/SECURITY_CONTACTS
  vendor/k8s.io/klog/v2/code-of-conduct.md
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/modules.txt
Labels: approved, lgtm

#214 Bug 1892376: Ignore if netns is already deleted while deleting ns
  pkg/network/master/vnids.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#201 Dockerfile: add tcpdump for debugging
  images/sdn/Dockerfile.rhel
Labels: approved, lgtm

#162 sdn: update to OVS 2.13
  images/sdn/Dockerfile.rhel
Labels: approved, lgtm

#215 [release-4.5] UPSTREAM<carry>: Bug 1880341: Fix bug in reflector not recovering from "Too large resource version"
  deps.diff
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apiserver/pkg/storage/errors.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#221 Make binaries not stripped
  Makefile
Labels: approved, lgtm
