Repository openshift/sdn, pull requests merged in 2020-12, with the labels that each got.

#225 [release-4.5] Bug 1901043: Enable conntrack for ovs-multitenant unless userspace proxy
  pkg/network/node/node.go
  pkg/network/node/ovs/ovs.go
  pkg/network/node/ovs/ovs_test.go
  pkg/network/node/ovscontroller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#220 Bug 1897073: Don't throw an error for control plane VNID
  pkg/network/master/vnids.go
  pkg/network/netid.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#210 Bug 1891454: Fix error handling from DNS nameservers
  pkg/network/common/dns.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#230 Bug 1906844: Handle unsupported EndpointSlice and EndpointSliceProxying feature gates
  pkg/openshift-sdn/proxy.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
