Repository openshift/sdn, pull requests merged in 2021-05, with the labels that each got.

#289 Bug 1879077: ValidateMTU: check only the interface that holds the node ip
  pkg/network/node/node.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#294 Bug 1928851: prevent manually creating netns with existing NetID
  pkg/network/node/vnids.go
  pkg/network/node/vnids_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#286 Bug 1923231: rebase to sdn-4.7-kubernetes-1.20.0-rc.0
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/BUILD
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#307 Bug 1964625: NETID duplicate check is only required in NetworkPolicy Mode
  pkg/network/node/multitenant.go
  pkg/network/node/networkpolicy.go
  pkg/network/node/node.go
  pkg/network/node/singletenant.go
  pkg/network/node/vnids.go
  pkg/network/node/vnids_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#303 Bug 1915849: Bump 4.6 to use OVS 2.13
  images/sdn/Dockerfile.rhel
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
