Repository openshift/sdn, pull requests merged in 2021-09, with the labels that each got.

#341 [release-4.8] Bug 1999946: improve SDN's OVS healthcheck and logging
  pkg/network/node/healthcheck.go
  pkg/network/node/healthcheck_ovs.go
  pkg/network/node/ovs/ovs.go
  pkg/network/node/sdn_controller.go
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#336 README minor improvements
  README.md
Labels: approved, lgtm

#333 Fix Dockerfile.fedora
  images/sdn/Dockerfile.fedora
Labels: approved, lgtm

#342 Bug 1966521: proxy: don't re-check every userspace proxy rule on every change
  go.mod
  go.sum
  pkg/network/proxy/hybridproxier.go
  pkg/network/proxy/proxy.go
  pkg/network/proxy/proxy_test.go
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier_openshift.go
  vendor/k8s.io/kubernetes/pkg/proxy/userspace/proxier.go
  vendor/k8s.io/kubernetes/pkg/proxy/userspace/proxier_openshift.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#343 [release-4.7] Bug 2001531: improve SDN's OVS healthcheck and logging
  pkg/network/node/healthcheck.go
  pkg/network/node/healthcheck_ovs.go
  pkg/network/node/ovs/ovs.go
  pkg/network/node/sdn_controller.go
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#340 [release-4.6] Bug 1998453: Fix MCS-blocking iptables rules
  cmd/sdn-cni-plugin/openshift-sdn_linux.go
  pkg/network/node/iptables.go
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#346 Bug 2002288: [4.9] proxy: don't re-check every userspace proxy rule on every change
  go.mod
  go.sum
  pkg/network/proxy/hybridproxier.go
  pkg/network/proxy/proxy.go
  pkg/network/proxy/proxy_test.go
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier_openshift.go
  vendor/k8s.io/kubernetes/pkg/proxy/userspace/proxier.go
  vendor/k8s.io/kubernetes/pkg/proxy/userspace/proxier_openshift.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high, staff-eng-approved

#353 [release-4.6] Bug 2004720: improve SDN's OVS healthcheck and logging
  pkg/network/node/healthcheck.go
  pkg/network/node/healthcheck_ovs.go
  pkg/network/node/ovs/ovs.go
  pkg/network/node/sdn_controller.go
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#352 resync proxy startup code with upstream
  pkg/cmd/openshift-sdn-node/cmd.go
  pkg/cmd/openshift-sdn-node/informers.go
  pkg/cmd/openshift-sdn-node/kube_proxy.go
  pkg/cmd/openshift-sdn-node/proxy.go
  pkg/network/proxy/hybridproxier.go
  pkg/network/proxy/hybridproxier_test.go
Labels: approved, lgtm

#349 Bug 2003859: Fix up event recorder usage (again)
  pkg/cmd/openshift-sdn-node/sdn.go
  pkg/network/node/node.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-low

#356 Replace utilruntime.HandleError() with klog.Errorf()
  pkg/cmd/openshift-sdn-node/cmd.go
  pkg/network/common/cniserver/cniserver.go
  pkg/network/common/common.go
  pkg/network/common/egress_dns.go
  pkg/network/common/egressip.go
  pkg/network/common/informers.go
  pkg/network/master/egressip.go
  pkg/network/master/master.go
  pkg/network/master/subnets.go
  pkg/network/master/vnids.go
  pkg/network/node/egress_network_policy.go
  pkg/network/node/egressip.go
  pkg/network/node/metrics/metrics.go
  pkg/network/node/multitenant.go
  pkg/network/node/networkpolicy.go
  pkg/network/node/node.go
  pkg/network/node/ovscontroller.go
  pkg/network/node/pod.go
  pkg/network/node/sdn_controller.go
  pkg/network/node/subnets.go
  pkg/network/proxy/hybridproxier.go
  pkg/network/proxy/proxy.go
  pkg/network/proxy/unidler/unidlersocket.go
  pkg/util/ovs/ovs.go
Labels: approved, lgtm

#348 Bug 2002291: [4.7] proxy: don't re-check every userspace proxy rule on every change
  go.mod
  go.sum
  pkg/network/proxy/proxy.go
  pkg/network/proxyimpl/hybrid/proxy.go
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier_openshift.go
  vendor/k8s.io/kubernetes/pkg/proxy/userspace/proxier.go
  vendor/k8s.io/kubernetes/pkg/proxy/userspace/proxier_openshift.go
  vendor/modules.txt
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high, qe-approved
