Repository openshift/sdn, pull requests merged in 2021-03, with the labels that each got.

#260 Bug 1924527: CVE-2021-3121 gogo/protobuf lacks certain index validation
  go.mod
  go.sum
  vendor/github.com/gogo/protobuf/proto/text_parser.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#261 [release-4.6] Bug 1928773: Prefer local endpoint for cluster DNS service
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#269 Bug 1910378: networkpolicy: pass traffic through NAT to handle possible tuple collisions
  pkg/network/node/networkpolicy.go
  pkg/network/node/ovscontroller.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#263 Bug 1933711: EgressDNS: Keep short lived records at most 30s
  pkg/network/common/dns.go
  pkg/network/common/dns_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#268 Bug 1935297: Prefer local endpoint for cluster DNS service
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#262 Support allow-from-router feature using openshift-host-network namespace
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
Labels: approved, lgtm

#275 Bug 1926931: Fix incorrect unmonitoring of egress nodes
  pkg/network/node/egressip.go
  pkg/network/node/vxlan_monitor.go
  pkg/network/node/vxlan_monitor_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#278 Add a networkpolicy test with empty namespaceSelector
  pkg/network/node/networkpolicy_test.go
Labels: approved, lgtm

#265 Bug 1924830: CVE-2021-3121 gogo/protobuf lacks certain index validation
  go.mod
  go.sum
  vendor/github.com/gogo/protobuf/proto/text_parser.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#282 Fix multiple race conditions in networkpolicy_test.go
  pkg/network/node/networkpolicy_test.go
Labels: approved, lgtm
