Repository openshift/sdn, pull requests merged in 2021-01, with the labels that each got.

#233 Bug 1905761: Fix IP list for empty Egress network policy
  pkg/network/node/networkpolicy.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#240 Bug 1914284: Don't try to generate NetworkPolicy flows for non-pod-network pods
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#241 Bug 1915007: Revert NetworkPolicy performance fixes (4.6)
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#242 Bug 1915008: Revert NetworkPolicy performance fixes (4.5)
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#243 Bug 1915027: Fix MCS-blocking iptables rules
  cmd/sdn-cni-plugin/openshift-sdn_linux.go
  pkg/network/node/iptables.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#239 Bug 1905761: Fix empty egress policy connectivity
  pkg/network/node/networkpolicy.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#238 Bug 1897478: Bump OVS to 2.13
  images/sdn/Dockerfile.rhel
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
