Repository openshift/sdn, pull requests merged in 2021-08, with the labels that each got.

#329 Bug 1989122: Fix hybrid proxier with EndpointSlice
  pkg/network/proxy/hybridproxier.go
  pkg/network/proxy/hybridproxier_test.go
  pkg/network/proxy/proxy_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#332 Bug 1991551: update usage of Events for 1.22 rebase
  pkg/cmd/openshift-sdn-node/proxy.go
  pkg/cmd/openshift-sdn-node/sdn.go
  pkg/network/node/node.go
  pkg/network/proxy/unidler/unidlerproxy.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#334 [release-4.7] Bug 1971669: Fix 4.7 SDN Egress Network Policy
  pkg/network/node/ovscontroller.go
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#335 Bug 1985336: Disable conntrack for vxlan traffic
  pkg/network/node/iptables.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#306 Bug 1958390: improve SDN's OVS healthcheck and logging
  pkg/network/node/healthcheck.go
  pkg/network/node/healthcheck_ovs.go
  pkg/network/node/sdn_controller.go
  pkg/util/ovs/ovs.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high
