Repository openshift/sdn, pull requests merged in 2021-02, with the labels that each got.

#211 Bug 1891455: Fix error handling from DNS nameservers
  pkg/network/common/dns.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#236 Bug 1903414: Do not use egressIP on reply packets
  pkg/network/node/ovscontroller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#248 Be less melodramatic when restarting due to OVS restart
  pkg/network/node/healthcheck.go
Labels: approved, lgtm

#251 Bug 1850060: Make DNS queries for egress network policy async
  pkg/network/common/dns.go
  pkg/network/common/dns_test.go
  pkg/network/common/egress_dns.go
  pkg/network/common/egress_dns_test.go
  pkg/network/common/fake_dns.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#249 Bug 1904455: NetworkPolicy performance fixes, v2
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#254 Bug 1919737: Prefer local endpoint for cluster DNS service
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
