Repository openshift/sdn, pull requests merged in 2021-04, with the labels that each got.

#276 Add a unit test to ensure we don't change flows without changing ruleVersion
  pkg/network/node/ovscontroller_test.go
Labels: approved, lgtm

#277 egress IP traffic load-balancing
  pkg/network/common/egressip.go
  pkg/network/common/egressip_test.go
  pkg/network/master/egressip.go
  pkg/network/node/egressip.go
  pkg/network/node/egressip_test.go
  pkg/network/node/ovs/fake_ovs.go
  pkg/network/node/ovs/ovs.go
  pkg/network/node/ovs/parse.go
  pkg/network/node/ovs/parse_test.go
  pkg/network/node/ovscontroller.go
  pkg/network/node/ovscontroller_test.go
Labels: approved, lgtm

#290 Bug 1952079: Don't require EndpointSlice to be disabled
  pkg/openshift-sdn/proxy.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#287 Bug 1948999: Remove check enforcing single egress IP for automatic assignment
  pkg/network/common/egressip.go
  pkg/network/common/egressip_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#293 Bug 1953530: Fix flaky unit test `TestEgressCIDRAllocation`
  pkg/network/common/egressip_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
