Repository openshift/sdn, pull requests merged in 2021-06, with the labels that each got.

#310 Bug 1960284: Bump openshift/kubernetes for "local-with-fallback"
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#295 Bug 1953257: Fix invalid egress IP assignments in sdn-controller
  pkg/network/common/egressip.go
  pkg/network/common/egressip_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#299 Bug 1959711: Reverse table order for egress IP and egress network policy set up
  pkg/network/node/egressip_test.go
  pkg/network/node/ovs/fake_ovs_test.go
  pkg/network/node/ovscontroller.go
  pkg/network/node/ovscontroller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#311 Bug 1948436: remove vxlan_monitor and OVS packet stat parsing
  pkg/network/node/egressip.go
  pkg/network/node/vxlan_monitor.go
  pkg/network/node/vxlan_monitor_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#315 [release-4.6] Bug 1970046: Fix for empty egress policy
  pkg/network/node/networkpolicy.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved

#312 fix a race condition in networkpolicy_test.go
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
Labels: approved, lgtm

#283 Remove Valadas from owners
  OWNERS
Labels: approved, lgtm

#320 Bug 1971808: fix local-with-fallback
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#316 Bug 1942122: when assigning and releasing egressIP try more than once before failing
  pkg/network/node/iptables.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
