Repository openshift/sdn, pull requests merged in 2022-03, with the labels that each got.

#404 Bug 2060553: Separate the allPodsSelected into egress and ingress
  pkg/network/node/networkpolicy.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high, qe-approved

#405 Bug 2060956: Separate the allPodsSelected into egress and ingress
  pkg/network/node/networkpolicy.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high, staff-eng-approved, qe-approved

#406 Bug 2060553: another fix for mixed ingress and egress policies
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#407 Bug 2060956: another fix for mixed ingress and egress policies
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high, staff-eng-approved

#408 Bug 2061916: mixed ingress and egress policies can result in half-isolated pods
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#409 Bug 2061919: Fix releasing egress IP in cloud environments
  pkg/network/node/egressip.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#401 Add unit tests for vxlan no track ip table rule
  pkg/network/node/iptables_test.go
  pkg/network/node/testing/fake_iptables.go
Labels: ok-to-test, approved, lgtm

#418 Bug 2062558: egressip: Continue to process other nodes if a node is not ready
  pkg/network/master/egressip.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high
