Repository openshift/sdn, pull requests merged in 2022-05, with the labels that each got.

#423 Bug 2016534: Masquerade in cluster traffic that is marked for egress IP
  pkg/network/node/iptables.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#428 Bug 2016534: Exclude the default drop bit from egress IP VNID
  pkg/network/node/egressip.go
  pkg/network/node/egressip_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#411 Bug 2052332: use pods cache during reattach processing
  pkg/cmd/openshift-sdn-node/cmd.go
  pkg/network/node/node.go
  pkg/network/node/pod.go
  pkg/util/ovs/ovs.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#413 Bug 2063970: delete stale UDP conntrack entries for loadbalancer IPs
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/modules.txt
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high, backport-risk-assessed

#430 [release-4.10] Bug 2082451: Masquerade in cluster traffic that is marked for egress IP
  pkg/network/node/egressip.go
  pkg/network/node/egressip_test.go
  pkg/network/node/iptables.go
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium, qe-approved, backport-risk-assessed
