Repository openshift/sdn, pull requests merged in 2022-10, with the labels that each got.

#457 [release-4.10] OCPBUGS-647: Fix OCP hack to prefer local DNS endpoints
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/modules.txt
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#466 [release-4.11] OCPBUGS-668: Fix DNS endpoint hack to prefer local instead of forcing it
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/modules.txt
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#467 [release-4.10] OCPBUGS-647: Fix DNS endpoint hack to prefer local instead of forcing it
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/modules.txt
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#470 OCPBUGS-69: Generate egress ip metrics for sdn node
  pkg/network/common/egressip.go
  pkg/network/common/egressip_test.go
  pkg/network/master/egressip.go
  pkg/network/master/master.go
  pkg/network/node/egressip.go
  pkg/network/node/metrics/metrics.go
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug, jira/severity-moderate

#468 [release-4.9] OCPBUGS-2204: Fix DNS endpoint hack to prefer local instead of forcing it
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/modules.txt
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#469 [release-4.8] OCPBUGS-2205: Fix DNS endpoint hack to prefer local instead of forcing it
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/modules.txt
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate
