Repository openshift/sdn, pull requests merged in 2022-06, with the labels that each got.

#432 Bug 2067865: Bump prometheus/client_golang to 1.11.1
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/build_info_pre_1.12.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/desc.go
  vendor/github.com/prometheus/client_golang/prometheus/expvar_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/prometheus/client_golang/prometheus/value.go
  vendor/github.com/prometheus/client_golang/prometheus/vec.go
  vendor/github.com/prometheus/client_golang/prometheus/wrap.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#426 Bug 2079958: Add TopologyAwareHints support in kube-proxy.
  pkg/cmd/openshift-sdn-node/kube_proxy.go
  pkg/network/proxy/hybridproxier.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-urgent

#436 [release-4.9] Bug 2093978: Remove node-tainting for too-small MTU
  pkg/network/node/node.go
  vendor/k8s.io/kubernetes/pkg/util/taints/taints.go
  vendor/modules.txt
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium, qe-approved, backport-risk-assessed
