Repository openshift/sdn, pull requests merged in 2023-02, with the labels that each got.

#498 OCPBUGS-4133: rebase kube to kube 1.25.4
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/delete.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/request/list_work_estimator.go
  vendor/k8s.io/kubernetes/cmd/kube-proxy/app/server.go
  vendor/k8s.io/kubernetes/cmd/kube-proxy/app/server_others.go
  vendor/k8s.io/kubernetes/pkg/proxy/node.go
  vendor/k8s.io/kubernetes/pkg/proxy/topology.go
  vendor/k8s.io/kubernetes/pkg/proxy/winkernel/proxier.go
  vendor/modules.txt
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/conn.go
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug, jira/valid-reference

#465 OCPBUGS-2106: fix network policy egress
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#495 OCPBUGS-5842: Add /usr/bin/oc to image
  images/sdn/Dockerfile.fedora
  images/sdn/Dockerfile.rhel
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug, jira/valid-reference

#503 OCPBUGS-6714: Initialize egress node monitoring struct with previous reachability status
  pkg/network/common/egressip.go
  pkg/network/common/egressip_test.go
  pkg/network/master/egressip.go
  pkg/network/node/egressip.go
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#497 OCPBUGS-6842: Handle race condition to setup default vnid flows
  pkg/network/node/networkpolicy.go
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#507 Drop non-conntrack-based Service support
  pkg/cmd/openshift-sdn-node/kube_proxy.go
  pkg/network/node/iptables.go
  pkg/network/node/iptables_test.go
  pkg/network/node/multitenant.go
  pkg/network/node/node.go
  pkg/network/node/ovscontroller.go
  pkg/network/node/ovscontroller_test.go
  pkg/network/node/sdn_controller.go
Labels: approved, lgtm

#506 [release-4.11] OCPBUGS-7515: Handle race condition to setup default vnid flows
  pkg/network/node/networkpolicy.go
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference
