Repository openshift/sdn, pull requests merged in 2023-05, with the labels that each got.

#535 OCPBUGS-12233: CVE-2018-17419 ose-node-container: dns: Denial of Service (DoS)
  go.mod
  go.sum
  vendor/github.com/miekg/dns/.travis.yml
  vendor/github.com/miekg/dns/CODEOWNERS
  vendor/github.com/miekg/dns/Gopkg.lock
  vendor/github.com/miekg/dns/Gopkg.toml
  vendor/github.com/miekg/dns/LICENSE
  vendor/github.com/miekg/dns/README.md
  vendor/github.com/miekg/dns/acceptfunc.go
  vendor/github.com/miekg/dns/client.go
  vendor/github.com/miekg/dns/clientconfig.go
  vendor/github.com/miekg/dns/defaults.go
  vendor/github.com/miekg/dns/dns.go
  vendor/github.com/miekg/dns/dnssec.go
  vendor/github.com/miekg/dns/dnssec_keygen.go
  vendor/github.com/miekg/dns/dnssec_keyscan.go
  vendor/github.com/miekg/dns/dnssec_privkey.go
  vendor/github.com/miekg/dns/doc.go
  vendor/github.com/miekg/dns/duplicate.go
  vendor/github.com/miekg/dns/edns.go
  vendor/github.com/miekg/dns/format.go
  vendor/github.com/miekg/dns/fuzz.go
  vendor/github.com/miekg/dns/generate.go
  vendor/github.com/miekg/dns/labels.go
  vendor/github.com/miekg/dns/listen_go111.go
  vendor/github.com/miekg/dns/listen_go_not111.go
  vendor/github.com/miekg/dns/msg.go
  vendor/github.com/miekg/dns/msg_helpers.go
  vendor/github.com/miekg/dns/msg_truncate.go
  vendor/github.com/miekg/dns/nsecx.go
  vendor/github.com/miekg/dns/privaterr.go
  vendor/github.com/miekg/dns/rawmsg.go
  vendor/github.com/miekg/dns/reverse.go
  vendor/github.com/miekg/dns/sanitize.go
  vendor/github.com/miekg/dns/scan.go
  vendor/github.com/miekg/dns/scan_rr.go
  vendor/github.com/miekg/dns/scanner.go
  vendor/github.com/miekg/dns/serve_mux.go
  vendor/github.com/miekg/dns/server.go
  vendor/github.com/miekg/dns/sig0.go
  vendor/github.com/miekg/dns/singleinflight.go
  vendor/github.com/miekg/dns/smimea.go
  vendor/github.com/miekg/dns/svcb.go
  vendor/github.com/miekg/dns/tlsa.go
  vendor/github.com/miekg/dns/tsig.go
  vendor/github.com/miekg/dns/types.go
  vendor/github.com/miekg/dns/udp_windows.go
  vendor/github.com/miekg/dns/update.go
  vendor/github.com/miekg/dns/version.go
  vendor/github.com/miekg/dns/xfr.go
  vendor/github.com/miekg/dns/zcompress.go
  vendor/github.com/miekg/dns/zduplicate.go
  vendor/github.com/miekg/dns/zmsg.go
  vendor/github.com/miekg/dns/ztypes.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug, jira/valid-reference

#534 OCPBUGS-13717: Use the ovsver build arg to infer the openvswitch short version number
  images/sdn/Dockerfile.rhel
Labels: bugzilla/valid-bug, approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#536 [release-4.13] OCPBUGS-12234: CVE-2018-17419 ose-node-container: dns: Denial of Service (DoS)
  go.mod
  go.sum
  vendor/github.com/miekg/dns/.travis.yml
  vendor/github.com/miekg/dns/CODEOWNERS
  vendor/github.com/miekg/dns/Gopkg.lock
  vendor/github.com/miekg/dns/Gopkg.toml
  vendor/github.com/miekg/dns/LICENSE
  vendor/github.com/miekg/dns/README.md
  vendor/github.com/miekg/dns/acceptfunc.go
  vendor/github.com/miekg/dns/client.go
  vendor/github.com/miekg/dns/clientconfig.go
  vendor/github.com/miekg/dns/defaults.go
  vendor/github.com/miekg/dns/dns.go
  vendor/github.com/miekg/dns/dnssec.go
  vendor/github.com/miekg/dns/dnssec_keygen.go
  vendor/github.com/miekg/dns/dnssec_keyscan.go
  vendor/github.com/miekg/dns/dnssec_privkey.go
  vendor/github.com/miekg/dns/doc.go
  vendor/github.com/miekg/dns/duplicate.go
  vendor/github.com/miekg/dns/edns.go
  vendor/github.com/miekg/dns/format.go
  vendor/github.com/miekg/dns/fuzz.go
  vendor/github.com/miekg/dns/generate.go
  vendor/github.com/miekg/dns/labels.go
  vendor/github.com/miekg/dns/listen_go111.go
  vendor/github.com/miekg/dns/listen_go_not111.go
  vendor/github.com/miekg/dns/msg.go
  vendor/github.com/miekg/dns/msg_helpers.go
  vendor/github.com/miekg/dns/msg_truncate.go
  vendor/github.com/miekg/dns/nsecx.go
  vendor/github.com/miekg/dns/privaterr.go
  vendor/github.com/miekg/dns/rawmsg.go
  vendor/github.com/miekg/dns/reverse.go
  vendor/github.com/miekg/dns/sanitize.go
  vendor/github.com/miekg/dns/scan.go
  vendor/github.com/miekg/dns/scan_rr.go
  vendor/github.com/miekg/dns/scanner.go
  vendor/github.com/miekg/dns/serve_mux.go
  vendor/github.com/miekg/dns/server.go
  vendor/github.com/miekg/dns/sig0.go
  vendor/github.com/miekg/dns/singleinflight.go
  vendor/github.com/miekg/dns/smimea.go
  vendor/github.com/miekg/dns/svcb.go
  vendor/github.com/miekg/dns/tlsa.go
  vendor/github.com/miekg/dns/tsig.go
  vendor/github.com/miekg/dns/types.go
  vendor/github.com/miekg/dns/udp_windows.go
  vendor/github.com/miekg/dns/update.go
  vendor/github.com/miekg/dns/version.go
  vendor/github.com/miekg/dns/xfr.go
  vendor/github.com/miekg/dns/zcompress.go
  vendor/github.com/miekg/dns/zduplicate.go
  vendor/github.com/miekg/dns/zmsg.go
  vendor/github.com/miekg/dns/ztypes.go
  vendor/modules.txt
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#543 [release-4.11] OCPBUGS-13902: CVE-2018-17419 ose-node-container: dns: Denial of Service (DoS) [openshift-4]
  go.mod
  go.sum
  vendor/github.com/miekg/dns/.travis.yml
  vendor/github.com/miekg/dns/CODEOWNERS
  vendor/github.com/miekg/dns/Gopkg.lock
  vendor/github.com/miekg/dns/Gopkg.toml
  vendor/github.com/miekg/dns/LICENSE
  vendor/github.com/miekg/dns/README.md
  vendor/github.com/miekg/dns/acceptfunc.go
  vendor/github.com/miekg/dns/client.go
  vendor/github.com/miekg/dns/clientconfig.go
  vendor/github.com/miekg/dns/defaults.go
  vendor/github.com/miekg/dns/dns.go
  vendor/github.com/miekg/dns/dnssec.go
  vendor/github.com/miekg/dns/dnssec_keygen.go
  vendor/github.com/miekg/dns/dnssec_keyscan.go
  vendor/github.com/miekg/dns/dnssec_privkey.go
  vendor/github.com/miekg/dns/doc.go
  vendor/github.com/miekg/dns/duplicate.go
  vendor/github.com/miekg/dns/edns.go
  vendor/github.com/miekg/dns/format.go
  vendor/github.com/miekg/dns/fuzz.go
  vendor/github.com/miekg/dns/generate.go
  vendor/github.com/miekg/dns/go.mod
  vendor/github.com/miekg/dns/go.sum
  vendor/github.com/miekg/dns/labels.go
  vendor/github.com/miekg/dns/listen_go111.go
  vendor/github.com/miekg/dns/listen_go_not111.go
  vendor/github.com/miekg/dns/msg.go
  vendor/github.com/miekg/dns/msg_helpers.go
  vendor/github.com/miekg/dns/msg_truncate.go
  vendor/github.com/miekg/dns/nsecx.go
  vendor/github.com/miekg/dns/privaterr.go
  vendor/github.com/miekg/dns/rawmsg.go
  vendor/github.com/miekg/dns/reverse.go
  vendor/github.com/miekg/dns/sanitize.go
  vendor/github.com/miekg/dns/scan.go
  vendor/github.com/miekg/dns/scan_rr.go
  vendor/github.com/miekg/dns/scanner.go
  vendor/github.com/miekg/dns/serve_mux.go
  vendor/github.com/miekg/dns/server.go
  vendor/github.com/miekg/dns/sig0.go
  vendor/github.com/miekg/dns/singleinflight.go
  vendor/github.com/miekg/dns/smimea.go
  vendor/github.com/miekg/dns/svcb.go
  vendor/github.com/miekg/dns/tlsa.go
  vendor/github.com/miekg/dns/tsig.go
  vendor/github.com/miekg/dns/types.go
  vendor/github.com/miekg/dns/udp_windows.go
  vendor/github.com/miekg/dns/update.go
  vendor/github.com/miekg/dns/version.go
  vendor/github.com/miekg/dns/xfr.go
  vendor/github.com/miekg/dns/zcompress.go
  vendor/github.com/miekg/dns/zduplicate.go
  vendor/github.com/miekg/dns/zmsg.go
  vendor/github.com/miekg/dns/ztypes.go
  vendor/modules.txt
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#544 [release-4.11] OCPBUGS-13917: save and delete the old egress network policy
  pkg/network/node/egress_network_policy.go
Labels: cherry-pick-approved, approved, lgtm, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#546 OCPBUGS-13975: fix possible concurrent map read/write
  pkg/network/node/networkpolicy.go
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#549 OCPBUGS-3176: Enable IP Forwarding if disabled
  pkg/network/node/sdn_controller.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#545 [release-4.10] OCPBUGS-13919: save and delete the old egress network policy
  pkg/network/node/egress_network_policy.go
Labels: cherry-pick-approved, approved, lgtm, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
