Repository openshift/sdn, pull requests merged in 2023-01, with the labels that each got.

#464 OCPBUGS-2105: fix network policy egress
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#488 OCPBUGS-998: [release-4.11] NetworkPolicy: Remove stale flows that may exist due to an upgrade
  pkg/network/node/networkpolicy.go
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, ¯\_(ツ)_/¯, backport-risk-assessed, jira/valid-bug

#487 [release-4.12] OCPBUGS-4486: Add node egress IP assignment resync
  pkg/network/node/egressip.go
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical

#496 iptables: use container iptables, not host's
  images/iptables-scripts/ip6tables
  images/iptables-scripts/ip6tables-restore
  images/iptables-scripts/ip6tables-save
  images/iptables-scripts/iptables
  images/iptables-scripts/iptables-restore
  images/iptables-scripts/iptables-save
  images/kube-proxy/Dockerfile.rhel
  images/sdn/Dockerfile.fedora
  images/sdn/Dockerfile.rhel
Labels: approved, lgtm

#490 Handle race condition to setup default vnid flows
  pkg/network/node/networkpolicy.go
Labels: approved, lgtm

#493 Add Tim R and remove Casey from OWNERS
  OWNERS
Labels: approved, lgtm
