Repository openshift/sdn, pull requests merged in 2023-03, with the labels that each got.

#494 [release-4.10] OCPBUGS-5977: Use pagination and set ResourceVersion to 0 when listing resources
  pkg/network/common/common.go
  pkg/network/common/common_test.go
  pkg/network/common/kube_list.go
  pkg/network/master/master.go
  pkg/network/master/subnets.go
  pkg/network/master/vnids.go
  pkg/network/node/egress_network_policy.go
  pkg/network/node/multitenant.go
  pkg/network/node/networkpolicy.go
  pkg/network/node/node.go
  pkg/network/node/vnids.go
  pkg/network/proxy/proxy.go
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#512 [release-4.10] OCPBUGS-8091: Handle race condition to setup default vnid flows
  pkg/network/node/networkpolicy.go
Labels: cherry-pick-approved, bugzilla/valid-bug, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#515 OCPBUGS-8007: Fix race in Egress IP Tracker start
  pkg/network/common/egressip.go
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#518 OCPBUGS-9985: Prefer local TCP endpoint for cluster DNS service
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference
