Repository openshift/sdn, pull requests merged in 2024-10, with the labels that each got.

#636 OCPBUGS-42203: fix UDP conntrack cleanup
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/proxy/endpoints.go
  vendor/modules.txt
Labels: cherry-pick-approved, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#635 OCPBUGS-43344: OCPBUGS-42244: Implement namespaceSelectors on ingress with all pods IPs
  pkg/network/node/networkpolicy.go
  pkg/network/node/networkpolicy_test.go
  pkg/network/node/ovscontroller.go
  pkg/network/node/ovscontroller_test.go
Labels: cherry-pick-approved, approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#638 OCPBUGS-43764: Revendor to a patched k/k with our prefer-local-DNS hack
  go.mod
  go.sum
  vendor/k8s.io/api/admissionregistration/v1/types.go
  vendor/k8s.io/api/admissionregistration/v1alpha1/types.go
  vendor/k8s.io/api/admissionregistration/v1beta1/types.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/client-go/applyconfigurations/internal/internal.go
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/k8s.io/component-base/version/.gitattributes
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/kubelet/types/pod_update.go
  vendor/k8s.io/kubernetes/pkg/proxy/config/config.go
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/k8s.io/mount-utils/mount_helper_unix.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference
